### ISSUE TITLE
Can't make it work behind Nginx reverse proxy

### ISSUE THREAD

**Issue by r3c4ll** [phpmyadmin/docker#160] opened 2018-05-01 13:54 UTC
I'm having an issue with phpmyadmin behind a nginx reverse proxy, my docker-compose.yml:
```yaml
version: '3'

services:
    reverse-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        privileged: true
        restart: always

    joomla:
        image: joomla
        restart: always
        links:
            - joomla_db:mysql
        environment:
            VIRTUAL_HOST: joomla.reverse.com
            JOOMLA_DB_HOST: joomla_db
            JOOMLA_DB_PASSWORD: example

    joomla-pma:
        image: phpmyadmin/phpmyadmin
        links:
            - joomla_db:mysql
        restart: always
        environment:
            VIRTUALHOST: joomla-pma.reverse.com
            PMA_ABSOLUTE_URI: http://joomla-pma.reverse.com/
            PMA_HOST: joomla_db
            PMA_USER: root
            PMA_PASSWORD: example

    joomla_db:
        image: mysql:5.6
        restart: always
        environment:
        MYSQL_ROOT_PASSWORD: example
```

My /etc/hosts:
```
127.0.0.1 localhost
127.0.0.1 joomla.reverse.com
127.0.0.1 joomla-pma.reverse.com
```

So joomla.reverse.com is working fine, but joomla-pma.reverse.com return a 503 Service Temporarily Unavailable by nginx/1.13.12.

Any help is welcome!

**Comment by GerkinDev** [comment] 2018-06-05 18:34
Hi,

First things first, please format correctly your config file using code tags. It's not really readable that way, and it won't encourage others to answer.

Then, about your problem, it seems you have a typo: `VIRTUALHOST` in your `joomla-php` service section should be `VIRTUAL_HOST`.

**Comment by williamdes** [comment] 2019-09-30 17:46
@r3c4ll Is this issue solved ?

> First things first, please format correctly your config file using code tags. It's not really readable that way, and it won't encourage others to answer.

I agree, did some formatting to understand the issue.

**Comment by williamdes** [comment] 2019-12-23 16:54
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2019-12-23 16:54 UTC
Labels: question
