### ISSUE TITLE
Docker hub registry confusion

### ISSUE THREAD

**Issue by atilsensalduz** [phpmyadmin/docker#428] opened 2023-09-20 14:20 UTC
Hi,

What is the difference between https://hub.docker.com/r/phpmyadmin/phpmyadmin and https://hub.docker.com/_/phpmyadmin? phpmyadmin/phpmyadmin doesn't have arm based images. Should that repository be deprecated? 🤔

**Comment by williamdes** [comment] 2023-09-21 07:34
Duplicate of #363

**Closed by williamdes** 2023-09-21 07:34 UTC

**Comment by williamdes** [comment] 2023-09-21 07:35
Thanks for asking the right questions, you can find more answers in #363
Feel free to let a message on the linked issue
