### ISSUE TITLE
docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/<string-of numbers>fb-init/merged: too many levels of symbolic links.

### ISSUE THREAD

**Issue by STaRDoGG** [phpmyadmin/docker#267] opened 2020-01-03 18:32 UTC
I'm trying to run this command:

```
docker run --name phpmyadmin -d -p 9024:80 --net='my-db' -e TZ='America/Chicago' -e PMA_HOST=mysql -e MYSQL_ROOT_PASSWORD='werewrew#FDFDS%^FDF' -e PMA_ABSOLUTE_URI='https://my.domain.rocks:3333/phpmyadmin/' -v '/f/Sites/myWeb/.config/PHPMyAdmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php' -v '/f/Sites/myWeb/.config/PHPMyAdmin/apache2.conf:/etc/apache2/apache2.conf' -v '/f/Sites/myWeb/.config/PHPMyAdmin/Saved:/saved' -v '/f/Sites/myWeb/.config/PHPMyAdmin/Upload:/upload' -v '/f/Sites/myWeb/.config/PHPMyAdmin/Themes/:/var/www/html/themes/' phpmyadmin/phpmyadmin:latest
```

But I keep getting the error:

> docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/[string-of-numbers]-init/merged: too many levels of symbolic links.

Any ideas why?

**Comment by williamdes** [comment] 2020-01-03 20:13
@STaRDoGG no idea, the issue is out of the scope of phpMyAdmin

But my advice would be to remove arguments from the command line until the error is not here.
You will then have found the error in your config :)

**Comment by ibennetch** [comment] 2020-01-04 16:27
I did look in to this, but the best answer I could find on StackOverflow
about these sorts of errors was someone saying essentially "that's one of
the quirks of Docker" — I couldn't find any better solution than that.

If you link fewer -v files does that work?

**Comment by STaRDoGG** [comment] 2020-01-17 07:35
Thanks for looking into this, guys.

I'm still wrestling with this issue:

https://stackoverflow.com/q/59782031/553663

I'm even getting it when I remove all volume mounts. i.e.  just running:

```
docker run --name phpmyadmin -d -p 9024:80 --net=my-db -e TZ=America/Chicago -e "PMA_HOST=mysql" -e "MYSQL_ROOT_PASSWORD=redacted" -e "PMA_ABSOLUTE_URI=https://my.domain.rocks:33333/phpmyadmin/" phpmyadmin/phpmyadmin:latest
Unable to find image 'phpmyadmin/phpmyadmin:latest' locally
latest: Pulling from phpmyadmin/phpmyadmin
8ec398bc0356: Already exists
85cf4fc86478: Already exists
970dadf4ccb6: Already exists
8c04561117a4: Already exists
d6b7434b63a2: Already exists
83d8859e9744: Already exists
9c3d824d0ad5: Already exists
0ff2f3c2c8ab: Extracting [==================================================>]  10.58MB/10.58MB
f7a2cdcb0840: Download complete
fe8c2411b50b: Download complete
aa0cb4375001: Download complete
96198bf1ad68: Download complete
5fe54d7827f9: Download complete
b14701794f98: Download complete
017ea991a64c: Download complete
b9fac930b192: Download complete
1807d0d7270b: Download complete
5fe7c1ba6fbd: Download complete
docker: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/32a716d9ae4c60363ebb11152502fba95ee7589bf28474ff9dbc93519f33b6a9/merged: too many levels of symbolic links.
See 'docker run --help'.
```

I only get this issue when trying to run the PHPMyAdmin container.

**Comment by williamdes** [comment] 2020-01-17 07:50
I am not sure this issue is for phpMyAdmin
Could you try to run the hello world image using the same command ?

**Comment by STaRDoGG** [comment] 2020-01-17 08:09
![image](https://user-images.githubusercontent.com/1524526/72594956-5c3ad780-38ce-11ea-9d84-73367e5809e2.png)


![image](https://user-images.githubusercontent.com/1524526/72594967-64931280-38ce-11ea-8b57-c74f6e0cfa2a.png)

**Comment by williamdes** [comment] 2020-01-17 08:16
@J0WI what do you think about this issue ?

**Comment by J0WI** [comment] 2020-01-17 13:31
Never heard about it. Is this Windows only?

>  Could you try to run the hello world image using the same command ?

The hello world image or the ubuntu base image are not comparable. Maybe you can try with `wordpress:apache` or `php:apache`?

**Comment by STaRDoGG** [comment] 2020-01-18 00:21
@J0WI AHA! You've hit on something. (But I'm not experienced enough w/docker yet to know what, lol).

![image](https://user-images.githubusercontent.com/1524526/72654658-0e69b200-3956-11ea-9351-91ed1a4dbc30.png)

Yes, I am running Docker Desktop in Win 10 x64, running Linux containers.

**Comment by J0WI** [comment] 2020-01-18 00:27
We can't help you here, I suggest that you try moving this issue to https://github.com/docker/for-win or https://github.com/docker-library/php :confused:

**Comment by STaRDoGG** [comment] 2020-01-18 00:30
@J0WI ok, thanks. Any ideas though? It seems like you sort of have an idea, based on the suggestion you gave that pointed right to itself.

I'll try the PHP issues area; the Docker issues apparently get ignored by and large:
https://github.com/docker/for-win/issues

**Comment by kukubadze** [comment] 2020-03-12 19:27
i had same error with other image, because of corrupted image. just deleted and pull image then it started to work

**Comment by Maelzin13** [comment] 2021-09-08 13:49
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/73b07c78e2fddeb494013ff4998318723eb5c8a5ba7c396210a7b534d3d87c31/merged: too many levels of symbolic links  

Alguém pode dar um help ?

**Comment by miro-balaz** [comment] 2022-02-16 22:40
https://github.com/docker/for-win/issues/5763#issuecomment-936254676

**Closed** 2023-03-09 20:56 UTC
Labels: invalid, question
