### ISSUE TITLE
changing port number and where to find compose.yml file

### ISSUE THREAD

**Issue by MhmdSuleiman** [phpmyadmin/docker#306] opened 2020-09-25 00:34 UTC
Greeting
i want to change port number for my running container.so how can change it?
 i want to know where can i found docker-compose.yml file if it's exist?
note that my docker image from "Usage with linked server"

**Comment by williamdes** [comment] 2020-09-25 07:21
Hi
I think this is a duplicate of https://github.com/phpmyadmin/docker/issues/138
Maybe https://github.com/phpmyadmin/docker/issues/138#issuecomment-599023714 would solve your issue

**Closed** 2020-11-08 13:18 UTC
Labels: duplicate, question
