### ISSUE TITLE
Docker error "Could not reliably determine the server's fully qualified domain name."

### ISSUE THREAD

**Issue by AbDhops** [phpmyadmin/docker#293] opened 2020-06-28 10:54 UTC
### Describe the bug
I am running mariadb and phpmyadmin in docker enviornment. Everything start smoothly. mariaDB server is running. However, phpmyadmin docker container complains about "AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message"

### To Reproduce
Use following docker compose to setup containers for mariaDB and phpmyadmin.
```yml
version: "3.7"

# to Enter in docker 
# docker exec -it some-mariadb bash
services:
  db:
    image: mariadb
    container_name: MariaDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: 'Europe/Berlin'
    ports:
      - 9306:3306
    volumes:
       - './database:/var/lib/mysql'

  myphpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: MyPhpAdmin
    restart: always
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: 'Europe/Berlin'
    ports:
      - 8086:80
 
```
In container log we see error `AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message`

### Expected behavior

~~PhpMyAdmin shall able to start normally.~~
phpMyAdmin should not show this warning

### Server configuration
- mariadb : docker
- phpmyadmin: docker

**Comment by williamdes** [comment] 2020-06-28 15:52
Hi
I moved this issue here, thank you for reporting it

I think "PhpMyAdmin shall able to start normally." is more "phpMyAdmin should not show this warning"

@J0WI do you have some opinions on this one?

**Comment by AbDhops** [comment] 2020-06-28 16:33
@williamdes Corrected expected behaviour...

**Comment by J0WI** [comment] 2020-06-29 15:26
This is kind of a non-issue and also not caused by the phpmyadmin image. You'll find the same behavior in all apache/php images.
If you care about the warning you can use `--hostname` or `hostname:` to assign a valid hostname to the container.

**Comment by williamdes** [comment] 2020-06-29 17:07
Thank you for the answer, since this can be removed with an option I am closing this one.

**Closed by williamdes** 2020-06-29 17:07 UTC
Labels: question

**Comment by AbDhops** [comment] 2020-06-29 17:22
Sorry, but I had tried that already. 
See docker compose, and error remains same... 

```
version: "3.7"

# to Enter in docker 
# docker exec -it some-mariadb bash
services:
  db:
    image: mariadb
    container_name: MariaDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: radio
      TZ: 'Europe/Berlin'
    ports:
      - 9306:3306
    volumes:
       - './database:/var/lib/mysql'

  myphpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: MyPhpAdmin
    restart: always
    hostname: database
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: test
      PMA_HOST: db
      TZ: 'Europe/Berlin'
    ports:
      - 8086:80
```

**Comment by J0WI** [comment] 2020-06-29 17:25
`database` is not a [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name#Syntax)

**Comment by AbDhops** [comment] 2020-06-30 10:43
Thanks, that does resolves the error...

**Comment by chiqui3d** [comment] 2021-04-18 19:22
`echo 'ServerName 127.0.0.1' >> /etc/apache2/apache2.conf`

**Comment by neoacevedo** [comment] 2021-09-29 16:20
My case: in Linux works without hostname, but in Windows, doesn't work.

I'm using the same docker compose file for both OS without to modify any hosts file.

**Comment by NODRT** [comment] 2023-05-29 13:27
> `echo 'ServerName 127.0.0.1' >> /etc/apache2/apache2.conf`

Where do I put this code to make my dockers work? I'm using Portainer. Is this something I update in Portainer, or do I update text files directly?

**Comment by ap0ca** [comment] 2025-04-11 17:10
In the docker-compose file it can be solved by adding custom command:
```
    command: >
      /bin/sh -c "echo 'ServerName 127.0.0.1' >> /etc/apache2/apache2.conf && /docker-entrypoint.sh apache2-foreground"
```
