### ISSUE TITLE
Docker repo missing version tags

### ISSUE THREAD

**Issue by johan-smits** [phpmyadmin/docker#229] opened 2019-06-12 08:47 UTC
### To Reproduce

The docker repo https://hub.docker.com/r/phpmyadmin/phpmyadmin/tags does not contain all release tags. It only has 4.9 and in the past the minor version was also available.

### Expected behavior

Have a 4.9.0.and a 4.9.0.1 tag

**Comment by williamdes** [comment] 2019-12-23 13:50
Duplicate of #256

**Closed by williamdes** 2019-12-23 13:50 UTC

**Comment by ibennetch** [comment] 2019-12-26 16:42
This should now be resolved, fixed by #259.
