### ISSUE TITLE
Image does not shutdown gracefully

### ISSUE THREAD

**Issue by gggeek** [phpmyadmin/docker#20] opened 2016-02-09 12:52 UTC
When shutting down the image, docker first sends a SIGTERM to the process used as ENTRYPOINT, then after 10 secs a SIGKILL.

The phpmyadmin image ignores the first signal.

Even though there is no probable data loss at stake, it would be nicer if the image stopped immediately, saving 10 secs of wait on every docker stop.

Two ways to do that come to my mind:
a- catch the signal in run.sh (but this means not using 'exec' as last command)
b- do not run as entrypoint for the webserver the std index.php from phpmyadmin, but have a 'startup' php script which sets up listening to signals then includes the default index.php

I can send a PR if you have any preference for either option...

**Comment by nijel** [comment] 2016-02-09 15:37
Maybe it would be better to replace php's builtin server with something better? I was thinking about using php-fpm and nginx...

**Comment by gggeek** [comment] 2016-02-09 15:51
@nijel possibly, but that would mean a fair amount of work...

**Comment by nijel** [comment] 2016-02-09 15:56
I know, but workarounding the problem as you've described doesn't sound as a perfect solution as well. Also there are dozen of docker containers using ``php -S``....

**Comment by mathos** [comment] 2016-06-09 23:06
I would certainly "+1" the idea of at least starting up of php-fpm vs just straight php (at the very least it allows you to reload your php.ini and seems to make php a bit more peppy).  However, the issue is more about killing and reaping -- no, you can put down the scythe, not that kind of reaping -- there is an often over-looked issue with docker containers and making sure they not only stop the process but do so in a goodly manner (i.e. properly disconnecting sockets, closing file handles and the like vs say violently ripping it out in the most catastrophic means) .  I highly recommend people to review this: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by nijel** [comment] 2016-06-10 10:40
I really think there should be some standard PHP container which does all things properly and where man could just include the web application to run. It doesn't make much sense to reinvent this for every PHP based application...

**Comment by gggeek** [comment] 2016-06-10 11:25
php-fpm + nginx containers I already have, and should be able to propose one.
Would you like the container to terminate when php-fpm ends?

**Comment by nijel** [comment] 2016-06-10 11:30
I have no clue :-). I maintain this, but my Docker experience is almost zero, so I'm really open to suggestions what is best approach...

**Comment by ssteinerx** [comment] 2016-06-15 00:04
@gggeek If you know how to do this, please make a pull request and I'll test and review.  Having this have to time out on a shutdown request is silly and time consuming every iteration...

**Comment by j-vizcaino** [comment] 2016-07-04 15:44
Any update on this?
One simple around this would be to install `tini` and launch php using it.
`tini` acts as a simple process reaper and is available in the alpine 3.4 community.

**Comment by ssteinerx** [comment] 2016-07-15 23:12
I did some research and the way that the command is being invoked leads to signals not being passed through.

Using:

    CMD ["/run.sh"]

puts PHP at process id 1, so it receives signals, but it doesn't shut down nicely with:

    docker stop myadmin

I.E., the `php -S` command doesn't gracefully shutdown even when the signal gets there.

[Century Link Article](https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/)

This image really, really, should not be using `php -S` as a server.  

I'll fix it when I have time.  

I need this, but can't ship anything using `php -S` so, soon, this will be holding me up...

**Comment by nijel** [comment] 2016-07-18 12:22
Indeed PHP's built in server is really more for testing than for production.

**Comment by nijel** [comment] 2016-08-28 07:19
Should be fixed since #48 has been merged.

**Closed by nijel** 2016-08-28 07:19 UTC
